spring.application.name=bakend
server.port=8888
#spring.security.user.name=admin
#spring.security.user.password=1234
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp

#define user env
url.index=/index
url.login=/login
url.logout=/logout

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:~/test
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.hm2ddl=update
spring.jpa.properties.fomat_sql=true
spring.jpa.properties.show_sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true